/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   control_message__init
                     (ControlMessage         *message)
{
  static const ControlMessage init_value = CONTROL_MESSAGE__INIT;
  *message = init_value;
}
size_t control_message__get_packed_size
                     (const ControlMessage *message)
{
  assert(message->base.descriptor == &control_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t control_message__pack
                     (const ControlMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &control_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t control_message__pack_to_buffer
                     (const ControlMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &control_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ControlMessage *
       control_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ControlMessage *)
     protobuf_c_message_unpack (&control_message__descriptor,
                                allocator, len, data);
}
void   control_message__free_unpacked
                     (ControlMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &control_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   control_response__init
                     (ControlResponse         *message)
{
  static const ControlResponse init_value = CONTROL_RESPONSE__INIT;
  *message = init_value;
}
size_t control_response__get_packed_size
                     (const ControlResponse *message)
{
  assert(message->base.descriptor == &control_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t control_response__pack
                     (const ControlResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &control_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t control_response__pack_to_buffer
                     (const ControlResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &control_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ControlResponse *
       control_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ControlResponse *)
     protobuf_c_message_unpack (&control_response__descriptor,
                                allocator, len, data);
}
void   control_response__free_unpacked
                     (ControlResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &control_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor control_message__field_descriptors[2] =
{
  {
    "namespace",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControlMessage, namespace_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControlMessage, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned control_message__field_indices_by_name[] = {
  0,   /* field[0] = namespace */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange control_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor control_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ControlMessage",
  "ControlMessage",
  "ControlMessage",
  "",
  sizeof(ControlMessage),
  2,
  control_message__field_descriptors,
  control_message__field_indices_by_name,
  1,  control_message__number_ranges,
  (ProtobufCMessageInit) control_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor control_response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ControlResponse, has_status),
    offsetof(ControlResponse, status),
    &control_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControlResponse, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned control_response__field_indices_by_name[] = {
  1,   /* field[1] = result */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange control_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor control_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ControlResponse",
  "ControlResponse",
  "ControlResponse",
  "",
  sizeof(ControlResponse),
  2,
  control_response__field_descriptors,
  control_response__field_indices_by_name,
  1,  control_response__number_ranges,
  (ProtobufCMessageInit) control_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue control_status__enum_values_by_number[2] =
{
  { "CONTROL_STATUS_SUCCESS", "CONTROL_STATUS__CONTROL_STATUS_SUCCESS", 0 },
  { "CONTROL_STATUS_FAILURE", "CONTROL_STATUS__CONTROL_STATUS_FAILURE", 1 },
};
static const ProtobufCIntRange control_status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex control_status__enum_values_by_name[2] =
{
  { "CONTROL_STATUS_FAILURE", 1 },
  { "CONTROL_STATUS_SUCCESS", 0 },
};
const ProtobufCEnumDescriptor control_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ControlStatus",
  "ControlStatus",
  "ControlStatus",
  "",
  2,
  control_status__enum_values_by_number,
  2,
  control_status__enum_values_by_name,
  1,
  control_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
