#include "camera_register_ov7725.h"

#include "program_utils.h"

// clang-format off
static struct camera_register camera_registers_ov7725[] = {
    {.address = 0x00, .name = "GAIN", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x01, .name = "BLUE", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x02, .name = "RED", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x03, .name = "GREEN", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x05, .name = "BAVG", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x06, .name = "GAVG", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x07, .name = "RAVG", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x08, .name = "AECH", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x09, .name = "COM2", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x0A, .name = "PID", .access = CAMREG_ACCESS_READ},
    {.address = 0x0B, .name = "VER", .access = CAMREG_ACCESS_READ},
    {.address = 0x0C, .name = "COM3", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x0D, .name = "COM4", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x0E, .name = "COM5", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x0F, .name = "COM6", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x10, .name = "AEC", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x11, .name = "CLKRC", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x12, .name = "COM7", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x13, .name = "COM8", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x14, .name = "COM9", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x15, .name = "COM10", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x16, .name = "REG16", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x17, .name = "HSTART", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x18, .name = "HSIZE", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x19, .name = "VSTRT", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x1A, .name = "VSIZE", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x1B, .name = "PSHFT", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x1C, .name = "MIDH", .access = CAMREG_ACCESS_READ},
    {.address = 0x1D, .name = "MIDL", .access = CAMREG_ACCESS_READ},
    {.address = 0x1F, .name = "LAEC", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x20, .name = "COM11", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x22, .name = "BDBase", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x23, .name = "BDMStep", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x24, .name = "AEW", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x25, .name = "AEB", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x26, .name = "VPT", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x28, .name = "REG28", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x29, .name = "HOutSize", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x2A, .name = "EXHCH", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x2B, .name = "EXHCL", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x2C, .name = "VOutSize", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x2D, .name = "ADVFL", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x2E, .name = "ADVFH", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x2F, .name = "YAVE", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x30, .name = "LumHTh", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x31, .name = "LumLTh", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x32, .name = "HREF", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x33, .name = "DM_LNL", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x34, .name = "DM_LNH", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x35, .name = "ADoff_B", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x36, .name = "ADoff_R", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x37, .name = "ADoff_Gb", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    {.address = 0x38, .name = "ADoff_Gr", .access = CAMREG_ACCESS_READ | CAMREG_ACCESS_WRITE},
    // TODO:
};
// clang-format on

struct camera_registers_struct camera_registers_struct_ov7725 = { .registers = camera_registers_ov7725,
                                                                  .length = NUM_ELEMS(camera_registers_ov7725) };
