/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

#ifndef PROTOBUF_C_message_2eproto__INCLUDED
#define PROTOBUF_C_message_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct ControlMessage ControlMessage;
typedef struct ControlResponse ControlResponse;


/* --- enums --- */

typedef enum _ControlStatus {
  CONTROL_STATUS__CONTROL_STATUS_SUCCESS = 0,
  CONTROL_STATUS__CONTROL_STATUS_FAILURE = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CONTROL_STATUS)
} ControlStatus;

/* --- messages --- */

struct  ControlMessage
{
  ProtobufCMessage base;
  char *namespace_;
  char *value;
};
#define CONTROL_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_message__descriptor) \
    , NULL, NULL }


struct  ControlResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_status;
  ControlStatus status;
  char *result;
};
#define CONTROL_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_response__descriptor) \
    , 0, CONTROL_STATUS__CONTROL_STATUS_SUCCESS, NULL }


/* ControlMessage methods */
void   control_message__init
                     (ControlMessage         *message);
size_t control_message__get_packed_size
                     (const ControlMessage   *message);
size_t control_message__pack
                     (const ControlMessage   *message,
                      uint8_t             *out);
size_t control_message__pack_to_buffer
                     (const ControlMessage   *message,
                      ProtobufCBuffer     *buffer);
ControlMessage *
       control_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_message__free_unpacked
                     (ControlMessage *message,
                      ProtobufCAllocator *allocator);
/* ControlResponse methods */
void   control_response__init
                     (ControlResponse         *message);
size_t control_response__get_packed_size
                     (const ControlResponse   *message);
size_t control_response__pack
                     (const ControlResponse   *message,
                      uint8_t             *out);
size_t control_response__pack_to_buffer
                     (const ControlResponse   *message,
                      ProtobufCBuffer     *buffer);
ControlResponse *
       control_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_response__free_unpacked
                     (ControlResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ControlMessage_Closure)
                 (const ControlMessage *message,
                  void *closure_data);
typedef void (*ControlResponse_Closure)
                 (const ControlResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    control_status__descriptor;
extern const ProtobufCMessageDescriptor control_message__descriptor;
extern const ProtobufCMessageDescriptor control_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_message_2eproto__INCLUDED */
