/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

#ifndef PROTOBUF_C_message_2eproto__INCLUDED
#define PROTOBUF_C_message_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct ControlSsdp ControlSsdp;
typedef struct ControlCameraCapture ControlCameraCapture;
typedef struct ControlCameraRegisterRead ControlCameraRegisterRead;
typedef struct ControlCameraRegisterWrite ControlCameraRegisterWrite;
typedef struct ControlMessage ControlMessage;
typedef struct ControlResponseSsdp ControlResponseSsdp;
typedef struct ControlResponseCameraCapture ControlResponseCameraCapture;
typedef struct ControlResponseCameraRegisterRead ControlResponseCameraRegisterRead;
typedef struct ControlResponseCameraRegisterWrite ControlResponseCameraRegisterWrite;
typedef struct ControlResponseError ControlResponseError;
typedef struct ControlResponseMessage ControlResponseMessage;


/* --- enums --- */

typedef enum _ControlResponseStatus {
  CONTROL_RESPONSE_STATUS__UNSPECIFIED = 0,
  CONTROL_RESPONSE_STATUS__SUCCESS = 1,
  CONTROL_RESPONSE_STATUS__UKNOWN_REQUEST = 2,
  CONTROL_RESPONSE_STATUS__INVALID_REQUEST = 3,
  CONTROL_RESPONSE_STATUS__INTERNAL_ERROR = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CONTROL_RESPONSE_STATUS)
} ControlResponseStatus;

/* --- messages --- */

struct  ControlSsdp
{
  ProtobufCMessage base;
  protobuf_c_boolean enable;
};
#define CONTROL_SSDP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_ssdp__descriptor) \
    , 0 }


struct  ControlCameraCapture
{
  ProtobufCMessage base;
  protobuf_c_boolean enable;
  protobuf_c_boolean use_heartbeat;
};
#define CONTROL_CAMERA_CAPTURE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_camera_capture__descriptor) \
    , 0, 0 }


struct  ControlCameraRegisterRead
{
  ProtobufCMessage base;
  char *register_name;
};
#define CONTROL_CAMERA_REGISTER_READ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_camera_register_read__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  ControlCameraRegisterWrite
{
  ProtobufCMessage base;
  char *register_name;
  uint32_t register_value;
};
#define CONTROL_CAMERA_REGISTER_WRITE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_camera_register_write__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


typedef enum {
  CONTROL_MESSAGE__REQUEST__NOT_SET = 0,
  CONTROL_MESSAGE__REQUEST_SSDP = 1,
  CONTROL_MESSAGE__REQUEST_CAMERA_CAPTURE = 2,
  CONTROL_MESSAGE__REQUEST_CAMERA_REGISTER_READ = 3,
  CONTROL_MESSAGE__REQUEST_CAMERA_REGISTER_WRITE = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CONTROL_MESSAGE__REQUEST__CASE)
} ControlMessage__RequestCase;

struct  ControlMessage
{
  ProtobufCMessage base;
  ControlMessage__RequestCase request_case;
  union {
    ControlSsdp *ssdp;
    ControlCameraCapture *camera_capture;
    ControlCameraRegisterRead *camera_register_read;
    ControlCameraRegisterWrite *camera_register_write;
  };
};
#define CONTROL_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_message__descriptor) \
    , CONTROL_MESSAGE__REQUEST__NOT_SET, {0} }


struct  ControlResponseSsdp
{
  ProtobufCMessage base;
};
#define CONTROL_RESPONSE_SSDP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_response_ssdp__descriptor) \
     }


struct  ControlResponseCameraCapture
{
  ProtobufCMessage base;
};
#define CONTROL_RESPONSE_CAMERA_CAPTURE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_response_camera_capture__descriptor) \
     }


struct  ControlResponseCameraRegisterRead
{
  ProtobufCMessage base;
  uint32_t register_value;
};
#define CONTROL_RESPONSE_CAMERA_REGISTER_READ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_response_camera_register_read__descriptor) \
    , 0 }


struct  ControlResponseCameraRegisterWrite
{
  ProtobufCMessage base;
};
#define CONTROL_RESPONSE_CAMERA_REGISTER_WRITE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_response_camera_register_write__descriptor) \
     }


struct  ControlResponseError
{
  ProtobufCMessage base;
  char *reason;
};
#define CONTROL_RESPONSE_ERROR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_response_error__descriptor) \
    , (char *)protobuf_c_empty_string }


typedef enum {
  CONTROL_RESPONSE_MESSAGE__RESPONSE__NOT_SET = 0,
  CONTROL_RESPONSE_MESSAGE__RESPONSE_SSDP = 2,
  CONTROL_RESPONSE_MESSAGE__RESPONSE_CAMERA_CAPTURE = 3,
  CONTROL_RESPONSE_MESSAGE__RESPONSE_CAMERA_REGISTER_READ = 4,
  CONTROL_RESPONSE_MESSAGE__RESPONSE_CAMERA_REGISTER_WRITE = 5,
  CONTROL_RESPONSE_MESSAGE__RESPONSE_ERROR = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CONTROL_RESPONSE_MESSAGE__RESPONSE__CASE)
} ControlResponseMessage__ResponseCase;

struct  ControlResponseMessage
{
  ProtobufCMessage base;
  ControlResponseStatus status;
  ControlResponseMessage__ResponseCase response_case;
  union {
    ControlResponseSsdp *ssdp;
    ControlResponseCameraCapture *camera_capture;
    ControlResponseCameraRegisterRead *camera_register_read;
    ControlResponseCameraRegisterWrite *camera_register_write;
    ControlResponseError *error;
  };
};
#define CONTROL_RESPONSE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&control_response_message__descriptor) \
    , CONTROL_RESPONSE_STATUS__UNSPECIFIED, CONTROL_RESPONSE_MESSAGE__RESPONSE__NOT_SET, {0} }


/* ControlSsdp methods */
void   control_ssdp__init
                     (ControlSsdp         *message);
size_t control_ssdp__get_packed_size
                     (const ControlSsdp   *message);
size_t control_ssdp__pack
                     (const ControlSsdp   *message,
                      uint8_t             *out);
size_t control_ssdp__pack_to_buffer
                     (const ControlSsdp   *message,
                      ProtobufCBuffer     *buffer);
ControlSsdp *
       control_ssdp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_ssdp__free_unpacked
                     (ControlSsdp *message,
                      ProtobufCAllocator *allocator);
/* ControlCameraCapture methods */
void   control_camera_capture__init
                     (ControlCameraCapture         *message);
size_t control_camera_capture__get_packed_size
                     (const ControlCameraCapture   *message);
size_t control_camera_capture__pack
                     (const ControlCameraCapture   *message,
                      uint8_t             *out);
size_t control_camera_capture__pack_to_buffer
                     (const ControlCameraCapture   *message,
                      ProtobufCBuffer     *buffer);
ControlCameraCapture *
       control_camera_capture__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_camera_capture__free_unpacked
                     (ControlCameraCapture *message,
                      ProtobufCAllocator *allocator);
/* ControlCameraRegisterRead methods */
void   control_camera_register_read__init
                     (ControlCameraRegisterRead         *message);
size_t control_camera_register_read__get_packed_size
                     (const ControlCameraRegisterRead   *message);
size_t control_camera_register_read__pack
                     (const ControlCameraRegisterRead   *message,
                      uint8_t             *out);
size_t control_camera_register_read__pack_to_buffer
                     (const ControlCameraRegisterRead   *message,
                      ProtobufCBuffer     *buffer);
ControlCameraRegisterRead *
       control_camera_register_read__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_camera_register_read__free_unpacked
                     (ControlCameraRegisterRead *message,
                      ProtobufCAllocator *allocator);
/* ControlCameraRegisterWrite methods */
void   control_camera_register_write__init
                     (ControlCameraRegisterWrite         *message);
size_t control_camera_register_write__get_packed_size
                     (const ControlCameraRegisterWrite   *message);
size_t control_camera_register_write__pack
                     (const ControlCameraRegisterWrite   *message,
                      uint8_t             *out);
size_t control_camera_register_write__pack_to_buffer
                     (const ControlCameraRegisterWrite   *message,
                      ProtobufCBuffer     *buffer);
ControlCameraRegisterWrite *
       control_camera_register_write__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_camera_register_write__free_unpacked
                     (ControlCameraRegisterWrite *message,
                      ProtobufCAllocator *allocator);
/* ControlMessage methods */
void   control_message__init
                     (ControlMessage         *message);
size_t control_message__get_packed_size
                     (const ControlMessage   *message);
size_t control_message__pack
                     (const ControlMessage   *message,
                      uint8_t             *out);
size_t control_message__pack_to_buffer
                     (const ControlMessage   *message,
                      ProtobufCBuffer     *buffer);
ControlMessage *
       control_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_message__free_unpacked
                     (ControlMessage *message,
                      ProtobufCAllocator *allocator);
/* ControlResponseSsdp methods */
void   control_response_ssdp__init
                     (ControlResponseSsdp         *message);
size_t control_response_ssdp__get_packed_size
                     (const ControlResponseSsdp   *message);
size_t control_response_ssdp__pack
                     (const ControlResponseSsdp   *message,
                      uint8_t             *out);
size_t control_response_ssdp__pack_to_buffer
                     (const ControlResponseSsdp   *message,
                      ProtobufCBuffer     *buffer);
ControlResponseSsdp *
       control_response_ssdp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_response_ssdp__free_unpacked
                     (ControlResponseSsdp *message,
                      ProtobufCAllocator *allocator);
/* ControlResponseCameraCapture methods */
void   control_response_camera_capture__init
                     (ControlResponseCameraCapture         *message);
size_t control_response_camera_capture__get_packed_size
                     (const ControlResponseCameraCapture   *message);
size_t control_response_camera_capture__pack
                     (const ControlResponseCameraCapture   *message,
                      uint8_t             *out);
size_t control_response_camera_capture__pack_to_buffer
                     (const ControlResponseCameraCapture   *message,
                      ProtobufCBuffer     *buffer);
ControlResponseCameraCapture *
       control_response_camera_capture__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_response_camera_capture__free_unpacked
                     (ControlResponseCameraCapture *message,
                      ProtobufCAllocator *allocator);
/* ControlResponseCameraRegisterRead methods */
void   control_response_camera_register_read__init
                     (ControlResponseCameraRegisterRead         *message);
size_t control_response_camera_register_read__get_packed_size
                     (const ControlResponseCameraRegisterRead   *message);
size_t control_response_camera_register_read__pack
                     (const ControlResponseCameraRegisterRead   *message,
                      uint8_t             *out);
size_t control_response_camera_register_read__pack_to_buffer
                     (const ControlResponseCameraRegisterRead   *message,
                      ProtobufCBuffer     *buffer);
ControlResponseCameraRegisterRead *
       control_response_camera_register_read__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_response_camera_register_read__free_unpacked
                     (ControlResponseCameraRegisterRead *message,
                      ProtobufCAllocator *allocator);
/* ControlResponseCameraRegisterWrite methods */
void   control_response_camera_register_write__init
                     (ControlResponseCameraRegisterWrite         *message);
size_t control_response_camera_register_write__get_packed_size
                     (const ControlResponseCameraRegisterWrite   *message);
size_t control_response_camera_register_write__pack
                     (const ControlResponseCameraRegisterWrite   *message,
                      uint8_t             *out);
size_t control_response_camera_register_write__pack_to_buffer
                     (const ControlResponseCameraRegisterWrite   *message,
                      ProtobufCBuffer     *buffer);
ControlResponseCameraRegisterWrite *
       control_response_camera_register_write__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_response_camera_register_write__free_unpacked
                     (ControlResponseCameraRegisterWrite *message,
                      ProtobufCAllocator *allocator);
/* ControlResponseError methods */
void   control_response_error__init
                     (ControlResponseError         *message);
size_t control_response_error__get_packed_size
                     (const ControlResponseError   *message);
size_t control_response_error__pack
                     (const ControlResponseError   *message,
                      uint8_t             *out);
size_t control_response_error__pack_to_buffer
                     (const ControlResponseError   *message,
                      ProtobufCBuffer     *buffer);
ControlResponseError *
       control_response_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_response_error__free_unpacked
                     (ControlResponseError *message,
                      ProtobufCAllocator *allocator);
/* ControlResponseMessage methods */
void   control_response_message__init
                     (ControlResponseMessage         *message);
size_t control_response_message__get_packed_size
                     (const ControlResponseMessage   *message);
size_t control_response_message__pack
                     (const ControlResponseMessage   *message,
                      uint8_t             *out);
size_t control_response_message__pack_to_buffer
                     (const ControlResponseMessage   *message,
                      ProtobufCBuffer     *buffer);
ControlResponseMessage *
       control_response_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   control_response_message__free_unpacked
                     (ControlResponseMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ControlSsdp_Closure)
                 (const ControlSsdp *message,
                  void *closure_data);
typedef void (*ControlCameraCapture_Closure)
                 (const ControlCameraCapture *message,
                  void *closure_data);
typedef void (*ControlCameraRegisterRead_Closure)
                 (const ControlCameraRegisterRead *message,
                  void *closure_data);
typedef void (*ControlCameraRegisterWrite_Closure)
                 (const ControlCameraRegisterWrite *message,
                  void *closure_data);
typedef void (*ControlMessage_Closure)
                 (const ControlMessage *message,
                  void *closure_data);
typedef void (*ControlResponseSsdp_Closure)
                 (const ControlResponseSsdp *message,
                  void *closure_data);
typedef void (*ControlResponseCameraCapture_Closure)
                 (const ControlResponseCameraCapture *message,
                  void *closure_data);
typedef void (*ControlResponseCameraRegisterRead_Closure)
                 (const ControlResponseCameraRegisterRead *message,
                  void *closure_data);
typedef void (*ControlResponseCameraRegisterWrite_Closure)
                 (const ControlResponseCameraRegisterWrite *message,
                  void *closure_data);
typedef void (*ControlResponseError_Closure)
                 (const ControlResponseError *message,
                  void *closure_data);
typedef void (*ControlResponseMessage_Closure)
                 (const ControlResponseMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    control_response_status__descriptor;
extern const ProtobufCMessageDescriptor control_ssdp__descriptor;
extern const ProtobufCMessageDescriptor control_camera_capture__descriptor;
extern const ProtobufCMessageDescriptor control_camera_register_read__descriptor;
extern const ProtobufCMessageDescriptor control_camera_register_write__descriptor;
extern const ProtobufCMessageDescriptor control_message__descriptor;
extern const ProtobufCMessageDescriptor control_response_ssdp__descriptor;
extern const ProtobufCMessageDescriptor control_response_camera_capture__descriptor;
extern const ProtobufCMessageDescriptor control_response_camera_register_read__descriptor;
extern const ProtobufCMessageDescriptor control_response_camera_register_write__descriptor;
extern const ProtobufCMessageDescriptor control_response_error__descriptor;
extern const ProtobufCMessageDescriptor control_response_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_message_2eproto__INCLUDED */
